server:
  port: 48082

spring:
  application:
    name: teros-api-gateway
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://10.10.2.102:8761/eureka}
  instance:
    preferIpAddress: true
# extra option
extra:
  env:
    teros_home: e:/teros_home